service: prsls-hello-world
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  version:
    handler: src/handlers/version.version
    name: prsls-version-${opt:stage, 'dev'}
    description: Service version
    events:
      - http:
          path: /version
          method: get
  healthz:
    handler: src/handlers/healthz.healthz
    name: prsls-healthz-${opt:stage, 'dev'}
    description: Service health
    events:
      - http:
          path: /healthz
          method: get
